language: dart
dart:
  - stable
  - dev
  - "2.6.0"
  - "2.6.1"
dart_task:
  - test: --platform vm
  - test: --platform chrome
  - test: --platform firefox
  - dartfmt: true
  - dartanalyzer: --fatal-infos --fatal-warnings lib test example
