name: json_api
version: 4.0.0
homepage: https://github.com/f3ath/json-api-dart
description: Framework-agnostic implementations of JSON:API Client and Server. Supports JSON:API v1.0 (http://jsonapi.org)
environment:
  sdk: '>=2.6.0 <3.0.0'
dependencies:
  http: ^0.12.0
dev_dependencies:
  html: ^0.14.0
  pedantic: ^1.9.0
  test: ^1.9.2
  json_matcher: ^0.2.3
  stream_channel: ^2.0.0
  uuid: ^2.0.1
  test_coverage: ^0.4.0
