author: "Alexey Karapetov <karapetov@gmail.com>"
description: "JSON:API Client for Flutter, Web and VM. Supports JSON:API v1.0 (http://jsonapi.org)"
homepage: "https://github.com/f3ath/json-api-dart"
name: "json_api"
version: "1.0.1"
dependencies:
  json_api_document: "^1.0.1"
  collection: "^1.14.11"
  http: "^0.12.0"
dev_dependencies:
  json_api_server: "^0.0.1"
  json_matcher: "^0.2.3"
  stream_channel: "^1.6.8"
  test: "^1.6.1"
  uuid: "^2.0.1"
environment: 
  sdk: ">=2.0.0 <3.0.0"
