author: "Alexey Karapetov <karapetov@gmail.com>"
description: "JSON:API Client for Flutter, VM and Web. Supports v1.0 of JSON:API (jsonapi.org)"
homepage: "https://github.com/f3ath/json-api-dart"
name: "json_api"
version: "0.6.0+1"
dependencies:
  json_api_document: "^0.5.0"
  collection: "^1.14.11"
  http: "^0.12.0"
dev_dependencies: 
  json_matcher: "^0.2.2"
  stream_channel: "^1.6.8"
  test: "^1.3.0"
  uuid: "^2.0.0"
environment: 
  sdk: ">=2.0.0 <3.0.0"
