author: "Alexey Karapetov <karapetov@gmail.com>"
description: "JSON:API v1.0 (http://jsonapi.org) Document, Client, and Server"
homepage: "https://github.com/f3ath/json-api-dart"
name: "json_api"
version: "0.6.0"
dependencies:
  json_api_document: "^1.0.0"
  collection: "^1.14.11"
  http: "^0.12.0"
dev_dependencies:
  json_api_server: "^0.0.1"
  json_matcher: "^0.2.3"
  stream_channel: "^1.6.8"
  test: "^1.3.0"
  uuid: "^2.0.0"
environment: 
  sdk: ">=2.0.0 <3.0.0"
